//------------------------------------------------------------------------------
// <auto-generated>
//     This code was manually generated to match GameInput.inputactions.
//     Normally this would be auto-generated by Unity's Input System.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;
using UnityEngine.InputSystem;

namespace TsumGame.Input
{
    /// <summary>
    /// GameInput.inputactions に対応する C# クラス
    /// </summary>
    public class GameInput
    {
        private InputActionAsset asset;
        private InputActionMap puzzleMap;

        public GameInput()
        {
            asset = Resources.Load<InputActionAsset>("GameInput");

            // Resourcesから読めない場合は、AssetDatabaseから直接読み込む
            if (asset == null)
            {
                asset = UnityEngine.Resources.Load<InputActionAsset>("GameInput");
            }

            // それでもnullの場合は、ランタイムで作成
            if (asset == null)
            {
                CreateInputActions();
            }
            else
            {
                puzzleMap = asset.FindActionMap("Puzzle");
            }
        }

        /// <summary>
        /// ランタイムでInput Actionsを作成
        /// </summary>
        private void CreateInputActions()
        {
            asset = ScriptableObject.CreateInstance<InputActionAsset>();

            // Puzzle Action Map作成
            puzzleMap = new InputActionMap("Puzzle");

            // Touch Action
            var touchAction = puzzleMap.AddAction("Touch", InputActionType.Button);
            touchAction.AddBinding("<Mouse>/leftButton");
            touchAction.AddBinding("<Touchscreen>/primaryTouch/press");

            // Position Action
            var positionAction = puzzleMap.AddAction("Position", InputActionType.Value, "<Vector2>");
            positionAction.AddBinding("<Mouse>/position");
            positionAction.AddBinding("<Touchscreen>/primaryTouch/position");

            asset.AddActionMap(puzzleMap);
        }

        public PuzzleActions Puzzle => new PuzzleActions(puzzleMap);

        public void Enable()
        {
            asset?.Enable();
        }

        public void Disable()
        {
            asset?.Disable();
        }

        public struct PuzzleActions
        {
            private InputActionMap map;

            public PuzzleActions(InputActionMap map)
            {
                this.map = map;
            }

            public InputAction Touch => map.FindAction("Touch");
            public InputAction Position => map.FindAction("Position");
        }
    }
}
